package com.beginner.hangdroid;

import android.content.Intent;
import android.os.Bundle;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.util.Log;
import android.view.View;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;

public class GameActivity extends AppCompatActivity {

    private String mWord = "WORD";

    private int mFailCounter = 0;

    private int mGuessedLetters = 0;

    private int mPoints = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_game);
        setRandomWord();

        /*Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Snackbar.make(view, "Replace with your own action", Snackbar.LENGTH_LONG)
                        .setAction("Action", null).show();
            }
        });*/
    }

    /**
     * Retrieving the letter introduced on the editText
     *
     * @param v (button clicked)
     */
    public void introduceLetter(View v){
        EditText myEditText = (EditText) findViewById(R.id.editTextLetter);

        String letter = myEditText.getText().toString();

        myEditText.setText("");

        Log.d("MYLOG", "The letter is " + letter);

        if(letter.length() == 1){
            checkLetter(letter.toUpperCase());
        }else{
            Toast.makeText(this,"Please introduce a letter",Toast.LENGTH_SHORT).show();
        }

    }

    /**
     * Checking if the letter introduced matches any letter in the word to guess
     *
     * @param introducedLetter letter introduced by the user
     */

    public void checkLetter(String introducedLetter){

        char charIntroduced  = introducedLetter.charAt(0);

        boolean letterGuessed = false;

        for (int i = 0; i < mWord.length() ; i++) {

            char charFromTheWord = mWord.charAt(i);

            Log.i("MYLOG","The letter we are checking is "+charFromTheWord);

            if(charFromTheWord == charIntroduced ){

                Log.i("MYLOG","There is one match");

                showLettersAtIndex(i, charIntroduced);

                letterGuessed = true;

                mGuessedLetters++;

                mPoints++;
            }

        }

        if(!letterGuessed){
            letterFailed(Character.toString(charIntroduced));
        }

        if(mGuessedLetters == mWord.length()){

            clearScreen();
            setRandomWord();
            // start the game again
        }
    }


    public void setRandomWord(){

        String words = "AAHS AALS ABAC ABAS ABBA ABBE ABBS ABED ABET ABID ABLE ABLY ABOSABRI ABUT ABYE ABYS ACAI ACCA ACED ACER ACES ACHE ACHY ACID ACMEACNE ACRE ACTA ACTS ACYL ADAW ADDS ADDY ADIT ADOS ADRY ADZE AEONAERO AERY AESC AFAR AFFY AFRO AGAR AGAS AGED AGEE AGEN AGER AGESAGHA AGIN AGIO AGLU AGLY AGMA AGOG AGON AGUE AHED AHEM AHIS AHOYAIAS AIDE AIDS AIGA AILS AIMS AINE AINS AIRN AIRS AIRT AIRY AITSAITU AJAR AJEE AKED AKEE AKES AKIN ALAE ALAN ALAP ALAR ALAS ALAYALBA ALBE ALBS ALCO ALEC ALEE ALEF ALES ALEW ALFA ALFS ALGA ALIFALIT ALKO ALKY ALLS ALLY ALMA ALME ALMS ALOD ALOE ALOW ALPS ALSOALTO ALTS ALUM AMAH AMAS AMBO AMEN AMIA AMID AMIE AMIN AMIR AMISAMLA AMMO AMOK AMPS AMUS AMYL ANAL ANAN ANAS ANCE ANDS ANES ANEWANGA ANIL ANIS ANKH ANNA ANNO ANNS ANOA ANON ANOW ANSA ANTA ANTEANTI ANTS ANUS APAY APED APER APES APEX APOD APOS APPS APSE APSOAPTS AQUA ARAK ARAR ARBA ARBS ARCH ARCO ARCS ARDS AREA ARED AREGARES ARET AREW ARFS ARIA ARID ARIL ARIS ARKS ARLE ARMS ARMY ARNAAROW ARPA ARSE ARSY ARTI ARTS ARTY ARUM ARVO ARYL ASAR ASCI ASEAASHY ASKS ASPS ATAP ATES ATMA ATOC ATOK ATOM ATOP ATUA AUFS AUKSAULA AULD AUNE AUNT AURA AUTO AVAL AVAS AVEL AVER AVES AVID AVOSAVOW AWAY AWDL AWED AWEE AWES AWLS AWNS AWNY AWOL AWRY AXAL AXEDAXEL AXES AXIL AXIS AXLE AXON AYAH AYES AYIN AYRE AYUS AZAN AZONAZYM BAAL BAAS BABA BABE BABU BABY BACH BACK BACS BADE BADS BAELBAFF BAFT BAGH BAGS BAHT BAIL BAIT BAJU BAKE BALD BALE BALK BALLBALM BALS BALU BAMS BANC BAND BANE BANG BANI BANK BANS BANT BAPSBAPU BARB BARD BARE BARF BARK BARM BARN BARP BARS BASE BASH BASKBASS BAST BATE BATH BATS BATT BAUD BAUK BAUR BAWD BAWL BAWN BAWRBAYE BAYS BAYT BEAD BEAK BEAM BEAN BEAR BEAT BEAU BECK BEDE BEDSBEDU BEEF BEEN BEEP BEER BEES BEET BEGO BEGS BEIN BELL BELS BELTBEMA BEND BENE BENI BENJ BENS BENT BERE BERG BERK BERM BEST BETABETE BETH BETS BEVY BEYS BHAT BHEL BHUT BIAS BIBB BIBS BICE BIDEBIDI BIDS BIEN BIER BIFF BIGA BIGG BIGS BIKE BILE BILK BILL BIMABIND BINE BING BINK BINS BINT BIOG BIOS BIRD BIRK BIRL BIRO BIRRBISE BISH BISK BIST BITE BITO BITS BITT BIZE BLAB BLAD BLAE BLAGBLAH BLAM BLAT BLAW BLAY BLEB BLED BLEE BLET BLEW BLEY BLIN BLIPBLOB BLOC BLOG BLOT BLOW BLUB BLUE BLUR BOAB BOAK BOAR BOAS BOATBOBA BOBS BOCK BODE BODS BODY BOEP BOET BOFF BOGS BOGY BOHO BOHSBOIL BOIS BOKE BOKO BOKS BOLA BOLD BOLE BOLL BOLO BOLT BOMA BOMBBONA BOND BONE BONG BONK BONY BOOB BOOH BOOK BOOL BOOM BOON BOORBOOS BOOT BOPS BORA BORD BORE BORK BORM BORN BORS BORT BOSH BOSKBOSS BOTA BOTH BOTS BOTT BOUK BOUN BOUT BOWL BOWR BOWS BOXY BOYFBOYG BOYO BOYS BOZO BRAD BRAE BRAG BRAK BRAN BRAS BRAT BRAW BRAYBRED BREE BREI BREN BRER BREW BREY BRIE BRIG BRIK BRIM BRIN BRIOBRIS BRIT BROD BROG BROO BROS BROW BRRR BRUS BRUT BRUX BUAT BUBABUBO BUBS BUBU BUCK BUDA BUDI BUDO BUDS BUFF BUFO BUGS BUHL BUHRBUIK BUKE BULB BULK BULL BUMF BUMP BUMS BUNA BUND BUNG BUNK BUNNBUNS BUNT BUOY BURA BURB BURD BURG BURK BURL BURN BURP BURR BURSBURY BUSH BUSK BUSS BUST BUSY BUTE BUTS BUTT BUYS BUZZ BYDE BYESBYKE BYRE BYRL BYTE CAAS CABA CABS CACA CADE CADI CADS CAFE CAFFCAGE CAGS CAGY CAID CAIN CAKE CAKY CALF CALK CALL CALM CALO CALPCALX CAMA CAME CAMO CAMP CAMS CANE CANG CANN CANS CANT CANY CAPACAPE CAPH CAPI CAPO CAPS CARB CARD CARE CARK CARL CARN CARP CARRCARS CART CASA CASE CASH CASK CAST CATE CATS CAUF CAUK CAUL CAUMCAUP CAVA CAVE CAVY CAWK CAWS CAYS CEAS CECA CEDE CEDI CEES CEILCELL CELS CELT CENS CENT CEPE CEPS CERE CERO CERT CESS CETE CHADCHAI CHAL CHAM CHAO CHAP CHAR CHAS CHAT CHAV CHAW CHAY CHEF CHERCHEW CHEZ CHIA CHIB CHIC CHID CHIK CHIN CHIP CHIS CHIT CHIV CHIZCHOC CHOG CHON CHOP CHOU CHOW CHUB CHUG CHUM CHUT CIAO CIDE CIDSCIEL CIGS CILL CINE CION CIRE CIRL CIST CITE CITO CITS CITY CIVECLAD CLAG CLAM CLAN CLAP CLAT CLAW CLAY CLEF CLEG CLEM CLEW CLIPCLOD CLOG CLON CLOP CLOT CLOU CLOW CLOY CLUB CLUE COAL COAT COAXCOBB COBS COCA COCH COCK COCO CODA CODE CODS COED COFF COFT COGSCOHO COIF COIL COIN COIR COIT COKE COKY COLA COLD COLE COLL COLSCOLT COLY COMA COMB COME COMM COMP COMS COND CONE CONF CONI CONKCONN CONS CONY COOF COOK COOL COOM COON COOP COOS COOT COPE COPSCOPY CORD CORE CORF CORK CORM CORN CORS CORY COSE COSH COSS COSTCOSY COTE COTH COTS COTT COUP COUR COVE COWK COWL COWP COWS COWYCOXA COXY COYS COZE COZY CRAB CRAG CRAM CRAN CRAP CRAW CRAY CREDCREE CREM CREW CRIB CRIM CRIS CRIT CROC CROG CROP CROW CRUD CRUECRUS CRUX CUBE CUBS CUDS CUED CUES CUFF CUIF CUIT CUKE CULL CULMCULT CUNT CUPS CURB CURD CURE CURF CURL CURN CURR CURS CURT CUSHCUSK CUSP CUSS CUTE CUTS CWMS CYAN CYMA CYME CYST CYTE CZAR DABSDACE DACK DADA DADO DADS DAES DAFF DAFT DAGO DAGS DAHL DAHS DAISDAKS DALE DALI DALS DALT DAME DAMN DAMP DAMS DANG DANK DANS DANTDAPS DARB DARE DARG DARI DARK DARN DART DASH DATA DATE DATO DAUBDAUD DAUR DAUT DAVY DAWD DAWK DAWN DAWS DAWT DAYS DAZE DEAD DEAFDEAL DEAN DEAR DEAW DEBE DEBS DEBT DECK DECO DEED DEEK DEEM DEENDEEP DEER DEES DEET DEEV DEFI DEFT DEFY DEGS DEID DEIF DEIL DEKEDELE DELF DELI DELL DELO DELS DELT DEME DEMO DEMY DENE DENI DENSDENT DENY DERE DERM DERN DERO DERV DESI DESK DEUS DEVA DEVS DEWSDEWY DEXY DEYS DHAK DHAL DHOL DHOW DIAL DIBS DICE DICH DICK DICTDIDO DIDY DIEB DIED DIEL DIES DIET DIFF DIFS DIGS DIKA DIKE DILLDIME DIMP DIMS DINE DING DINK DINO DINS DINT DIOL DIPS DIPT DIREDIRK DIRL DIRT DISA DISC DISH DISK DISS DITA DITE DITS DITT DITZDIVA DIVE DIVI DIVS DIXI DIXY DJIN DOAB DOAT DOBS DOBY DOCK DOCODOCS DODO DODS DOEK DOEN DOER DOES DOFF DOGE DOGS DOGY DOHS DOITDOJO DOLE DOLL DOLS DOLT DOME DOMS DOMY DONA DONE DONG DONS DOOBDOOK DOOL DOOM DOON DOOR DOOS DOPA DOPE DOPS DOPY DORB DORE DORKDORM DORP DORR DORS DORT DORY DOSE DOSH DOSS DOST DOTE DOTH DOTSDOTY DOUC DOUK DOUM DOUN DOUP DOUR DOUT DOUX DOVE DOWD DOWF DOWLDOWN DOWP DOWS DOWT DOXY DOYS DOZE DOZY DRAB DRAC DRAD DRAG DRAMDRAP DRAT DRAW DRAY DREE DREG DREK DREW DREY DRIB DRIP DROP DROWDRUB DRUG DRUM DRYS DSOS DUAD DUAL DUAN DUAR DUBS DUCE DUCI DUCKDUCT DUDE DUDS DUED DUEL DUES DUET DUFF DUGS DUIT DUKA DUKE DULEDULL DULY DUMA DUMB DUMP DUNE DUNG DUNK DUNS DUNT DUOS DUPE DUPSDURA DURE DURN DURO DURR DUSH DUSK DUST DUTY DWAM DYAD DYED DYERDYES DYKE DYNE DZHO DZOS EACH EALE EANS EARD EARL EARN EARS EASEEAST EASY EATH EATS EAUS EAUX EAVE EBBS EBON ECAD ECCE ECCO ECHEECHO ECHT ECOD ECOS ECRU ECUS EDDO EDDY EDGE EDGY EDHS EDIT EECHEELS EELY EERY EEVN EFFS EFTS EGAD EGAL EGER EGGS EGGY EGIS EGMAEGOS EHED EIDE EIKS EILD EINA EINE EISH EKED EKES EKKA ELAN ELDSELFS ELHI ELKS ELLS ELMS ELMY ELSE ELTS EMES EMEU EMIC EMIR EMITEMMA EMMY EMOS EMPT EMUS EMYD EMYS ENDS ENES ENEW ENGS ENOL ENOWENUF ENVY EOAN EONS EORL EPEE EPHA EPIC EPOS ERAS ERED ERES EREVERGO ERGS ERIC ERKS ERNE ERNS EROS ERRS ERST ERUV ESES ESKY ESNEESPY ESSE ESTS ETAS ETAT ETCH ETEN ETHE ETHS ETIC ETNA ETUI EUGEEUGH EUKS EUOI EURO EVEN EVER EVES EVET EVIL EVOE EVOS EWER EWESEWKS EWTS EXAM EXEC EXED EXES EXIT EXON EXPO EXUL EYAS EYED EYENEYER EYES EYNE EYOT EYRA EYRE EYRY FAAN FAAS FABS FACE FACT FADEFADO FADS FADY FAFF FAGS FAHS FAIK FAIL FAIN FAIR FAIX FAKE FALLFALX FAME FAND FANE FANG FANK FANO FANS FARD FARE FARL FARM FAROFARS FART FASH FAST FATE FATS FAUN FAUR FAUT FAUX FAVA FAVE FAWNFAWS FAYS FAZE FEAL FEAR FEAT FECK FEDS FEEB FEED FEEL FEEN FEERFEES FEET FEGS FEHM FEHS FEIS FELL FELT FEME FEMS FEND FENI FENSFENT FEOD FERE FERM FERN FESS FEST FETA FETE FETS FETT FEUD FEUSFEYS FIAR FIAT FIBS FICE FICO FIDO FIDS FIEF FIER FIFE FIFI FIGOFIGS FIKE FIKY FILA FILE FILL FILM FILO FILS FIND FINE FINI FINKFINO FINS FIRE FIRK FIRM FIRN FIRS FISC FISH FISK FIST FITS FITTFIVE FIXT FIZZ FLAB FLAG FLAK FLAM FLAN FLAP FLAT FLAW FLAX FLAYFLEA FLED FLEE FLEG FLEW FLEX FLEY FLIC FLIM FLIP FLIR FLIT FLIXFLOC FLOE FLOG FLOP FLOR FLOW FLUB FLUE FLUS FLUX FOAL FOAM FOBSFOCI FOEN FOES FOGS FOGY FOHN FOHS FOID FOIL FOIN FOLD FOLK FONDFONE FONS FONT FOOD FOOL FOOT FOPS FORA FORB FORD FORE FORK FORMFORT FOSS FOUD FOUL FOUR FOUS FOWL FOXY FOYS FOZY FRAB FRAE FRAGFRAP FRAS FRAT FRAU FRAY FREE FRET FRIB FRIG FRIS FRIT FRIZ FROEFROG FROM FROS FROW FRUG FUBS FUCI FUCK FUDS FUEL FUFF FUGS FUGUFUJI FULL FUME FUMS FUMY FUND FUNG FUNK FUNS FURL FURR FURS FURYFUSC FUSE FUSS FUST FUTZ FUZE FUZZ FYCE FYKE FYLE FYRD GABS GABYGADE GADI GADS GAED GAEN GAES GAFF GAGA GAGE GAGS GAID GAIN GAIRGAIT GAJO GALA GALE GALL GALS GAMA GAMB GAME GAMP GAMS GAMY GANEGANG GANS GANT GAOL GAPE GAPO GAPS GAPY GARB GARE GARI GARS GARTGASH GASP GAST GATE GATH GATS GAUD GAUM GAUN GAUP GAUR GAUS GAVEGAWD GAWK GAWP GAYS GAZE GAZY GEAL GEAN GEAR GEAT GECK GEDS GEEDGEEK GEEP GEES GEEZ GEIT GELD GELS GELT GEMS GENA GENE GENS GENTGENU GEOS GERE GERM GERT GEST GETA GETS GEUM GHAT GHEE GHIS GIBEGIBS GIDS GIED GIEN GIES GIFT GIGA GIGS GILA GILD GILL GILT GIMPGING GINK GINN GINS GIOS GIPS GIRD GIRL GIRN GIRO GIRR GIRT GISMGIST GITE GITS GIVE GIZZ GJUS GLAD GLAM GLED GLEE GLEG GLEI GLENGLEY GLIA GLIB GLID GLIM GLIT GLOB GLOM GLOP GLOW GLUE GLUG GLUMGLUT GNAR GNAT GNAW GNOW GNUS GOAD GOAF GOAL GOAS GOAT GOBO GOBSGOBY GODS GOEL GOER GOES GOEY GOFF GOGO GOLD GOLE GOLF GOLP GONEGONG GONK GONS GOOD GOOF GOOG GOOK GOOL GOON GOOP GOOR GOOS GORAGORE GORI GORM GORP GORY GOSH GOSS GOTH GOUK GOUT GOVS GOWD GOWFGOWK GOWL GOWN GOYS GRAB GRAD GRAM GRAN GRAT GRAV GRAY GREE GRENGREW GREX GREY GRID GRIG GRIM GRIN GRIP GRIS GRIT GROG GROK GROTGROW GRUB GRUE GRUM GUAN GUAR GUBS GUCK GUDE GUES GUFF GUGA GUIDGULA GULE GULF GULL GULP GULS GULY GUMP GUMS GUNG GUNK GUNS GUPSGURL GURN GURS GURU GUSH GUST GUTS GUVS GUYS GYAL GYBE GYMP GYMSGYNY GYPS GYRE GYRI GYRO GYTE GYVE HAAF HAAR HABU HACK HADE HADJHADS HAED HAEM HAEN HAES HAET HAFF HAFT HAGG HAGS HAHA HAHS HAIKHAIL HAIN HAIR HAJI HAJJ HAKA HAKE HAKU HALE HALF HALL HALM HALOHALT HAME HAMS HAND HANG HANK HANT HAPS HAPU HARD HARE HARK HARLHARM HARN HARO HARP HART HASH HASK HASP HAST HATE HATH HATS HAUDHAUF HAUL HAUT HAVE HAWK HAWM HAWS HAYS HAZE HAZY HEAD HEAL HEAPHEAR HEAT HEBE HECH HECK HEED HEEL HEFT HEHS HEID HEIL HEIR HELDHELE HELL HELM HELO HELP HEME HEMP HEMS HEND HENS HENT HEPS HEPTHERB HERD HERE HERL HERM HERN HERO HERS HERY HESP HEST HETE HETHHETS HEWN HEWS HEYS HICK HIDE HIED HIES HIGH HIKE HILA HILD HILIHILL HILT HIMS HIND HING HINS HINT HIOI HIPS HIPT HIRE HISH HISNHISS HIST HITS HIVE HIYA HIZZ HOAR HOAS HOAX HOBO HOBS HOCK HODSHOED HOER HOES HOGG HOGH HOGS HOHA HOHS HOIK HOKA HOKE HOKI HOLDHOLE HOLK HOLM HOLP HOLS HOLT HOLY HOMA HOME HOMO HOMS HOMY HONDHONE HONG HONK HONS HOOD HOOF HOOK HOON HOOP HOOT HOPE HOPS HORAHORE HORI HORN HORS HOSE HOSS HOST HOTE HOTS HOUF HOUR HOUT HOVEHOWE HOWF HOWK HOWL HOWS HOYA HOYS HUBS HUCK HUED HUER HUES HUFFHUGE HUGS HUGY HUHU HUIA HUIC HUIS HULA HULE HULK HULL HUMA HUMFHUMP HUMS HUNG HUNH HUNK HUNS HUNT HUPS HURL HURT HUSH HUSK HUSOHUSS HUTS HWAN HWYL HYED HYEN HYES HYKE HYLA HYLE HYMN HYPE HYPOHYPS HYTE IAMB IBEX IBIS ICED ICER ICES ICHS ICKY ICON IDEA IDEEIDEM IDES IDLE IDLY IDOL IDYL IFFY IGAD IGGS IGLU IKAN IKAT IKONILEA ILEX ILIA ILKA ILKS ILLS ILLY IMAM IMID IMMY IMPI IMPS INBYINCH INFO INGO INIA INKS INKY INLY INNS INRO INTI INTO IONS IOTAIRED IRES IRID IRIS IRKS IRON ISBA ISIT ISLE ISMS ISNA ISOS ITASITCH ITEM IURE IWIS IXIA IZAR JAAP JABS JACK JADE JAFA JAGA JAGGJAGS JAIL JAKE JAKS JAMB JAMS JANE JANN JAPE JAPS JARK JARL JARPJARS JASP JASS JASY JATO JAUK JAUP JAVA JAWS JAXY JAYS JAZY JAZZJEAN JEAT JEDI JEED JEEL JEEP JEER JEES JEEZ JEFE JEFF JEHU JELLJEON JERK JESS JEST JETE JETS JEUX JEWS JIAO JIBB JIBE JIBS JIFFJIGS JILL JILT JIMP JINK JINN JINS JINX JIRD JISM JIVE JIVY JIZZJOBE JOBS JOCK JOCO JOES JOEY JOGS JOHN JOIN JOKE JOKY JOLE JOLLJOLS JOLT JOMO JONG JOOK JORS JOSH JOSS JOTA JOTS JOUK JOUR JOWLJOWS JOYS JUBA JUBE JUCO JUDO JUDS JUDY JUGA JUGS JUJU JUKE JUKUJUMP JUNK JUPE JURA JURE JURY JUST JUTE JUTS JUVE JYNX KAAL KAASKABS KADE KADI KAED KAES KAFS KAGO KAGU KAID KAIE KAIF KAIK KAILKAIM KAIN KAIS KAKA KAKI KAKS KALE KALI KAMA KAME KAMI KANA KANEKANG KANS KANT KAON KAPA KAPH KARA KARK KARN KARO KART KATA KATIKATS KAVA KAWA KAWS KAYO KAYS KAZI KBAR KEAS KEBS KECK KEDS KEEFKEEK KEEL KEEN KEEP KEET KEFS KEGS KEIR KEKS KELL KELP KELT KEMBKEMP KENO KENS KENT KEPI KEPS KEPT KERB KERF KERN KERO KESH KESTKETA KETE KETO KETS KEWL KEYS KHAF KHAN KHAT KHET KHIS KHOR KHUDKIBE KICK KIDS KIEF KIER KIFF KIFS KIKE KILD KILL KILN KILO KILPKILT KINA KIND KINE KING KINK KINO KINS KIPE KIPP KIPS KIRK KIRNKIRS KISH KISS KIST KITE KITH KITS KIVA KIWI KLAP KLIK KNAG KNAPKNAR KNEE KNEW KNIT KNOB KNOP KNOT KNOW KNUB KNUR KNUT KOAN KOAPKOAS KOBO KOBS KOEL KOFF KOHA KOHL KOIS KOJI KOLA KOLO KOND KONKKONS KOOK KOPH KOPS KORA KORE KORO KORS KORU KOSS KOTO KOWS KRABKRIS KSAR KUDO KUDU KUEH KUES KUFI KUIA KUKU KULA KUNA KUNE KURIKURU KUTA KUTI KUTU KUZU KVAS KYAK KYAR KYAT KYBO KYES KYLE KYNDKYNE KYPE KYTE KYUS LABS LACE LACK LACS LACY LADE LADS LADY LAERLAGS LAHS LAIC LAID LAIK LAIN LAIR LAKE LAKH LAKY LALL LAMA LAMBLAME LAMP LAMS LANA LAND LANE LANG LANK LANT LANX LAPS LARD LARELARI LARK LARN LARS LASE LASH LASS LAST LATE LATH LATI LATS LATULAUD LAUF LAVA LAVE LAVS LAWK LAWN LAWS LAYS LAZE LAZO LAZY LEADLEAF LEAK LEAL LEAM LEAN LEAP LEAR LEAS LEAT LECH LEED LEEK LEEPLEER LEES LEET LEFT LEGS LEHR LEIR LEIS LEKE LEKS LEKU LEME LENDLENG LENO LENS LENT LEPS LEPT LERE LERP LESS LEST LETS LEUD LEVALEVE LEVO LEVY LEWD LEYS LEZZ LIAR LIAS LIBS LICE LICH LICK LIDOLIDS LIED LIEF LIEN LIER LIES LIEU LIFE LIFT LIGS LIKE LILL LILOLILT LILY LIMA LIMB LIME LIMN LIMO LIMP LIMY LIND LINE LING LINKLINN LINO LINS LINT LINY LION LIPA LIPE LIPO LIPS LIRA LIRE LIRILIRK LISK LISP LIST LITE LITH LITS LITU LIVE LOAD LOAF LOAM LOANLOBE LOBI LOBO LOBS LOCA LOCH LOCI LOCK LOCO LODE LODS LOFT LOGELOGO LOGS LOGY LOID LOIN LOIR LOKE LOLL LOMA LOME LONE LONG LOOFLOOK LOOM LOON LOOP LOOR LOOS LOOT LOPE LOPS LORD LORE LORN LORYLOSE LOSH LOSS LOST LOTA LOTE LOTH LOTI LOTO LOTS LOUD LOUN LOUPLOUR LOUS LOUT LOVE LOWE LOWN LOWP LOWS LOWT LOYS LUAU LUBE LUCELUCK LUDE LUDO LUDS LUES LUFF LUGE LUGS LUIT LUKE LULL LULU LUMALUMP LUMS LUNA LUNE LUNG LUNK LUNT LUNY LURE LURK LURS LUSH LUSKLUST LUTE LUTZ LUVS LUXE LWEI LYAM LYCH LYES LYME LYMS LYNE LYNXLYRA LYRE LYSE LYTE MAAR MAAS MABE MACE MACH MACK MACS MADE MADSMAES MAGE MAGG MAGI MAGS MAID MAIK MAIL MAIM MAIN MAIR MAKE MAKIMAKO MAKS MALA MALE MALI MALL MALM MALS MALT MAMA MAMS MANA MANDMANE MANG MANI MANO MANS MANY MAPS MARA MARC MARD MARE MARG MARKMARL MARM MARS MART MARY MASA MASE MASH MASK MASS MAST MASU MATEMATH MATS MATT MATY MAUD MAUL MAUN MAUT MAWK MAWN MAWR MAWS MAXIMAYA MAYO MAYS MAZE MAZY MEAD MEAL MEAN MEAT MECK MEDS MEED MEEKMEER MEES MEET MEFF MEGA MEGS MEIN MELA MELD MELL MELS MELT MEMEMEMO MEMS MEND MENE MENG MENO MENT MENU MEOU MEOW MERC MERE MERIMERK MERL MESA MESE MESH MESS META METE METH METS MEUS MEVE MEWLMEWS MEZE MEZZ MHOS MIBS MICA MICE MICH MICK MICO MICS MIDI MIDSMIEN MIFF MIGG MIGS MIHA MIHI MIKE MILD MILE MILK MILL MILO MILSMILT MIME MINA MIND MINE MING MINI MINK MINO MINT MINX MINY MIPSMIRE MIRI MIRK MIRO MIRS MIRV MIRY MISE MISO MISS MIST MITE MITTMITY MIXT MIXY MIZZ MNAS MOAI MOAN MOAS MOAT MOBE MOBS MOBY MOCHMOCK MOCS MODE MODI MODS MOER MOES MOFO MOGS MOHR MOIL MOIT MOJOMOKE MOKI MOKO MOLA MOLD MOLE MOLL MOLS MOLT MOLY MOME MOMI MOMSMONA MONG MONK MONO MONS MONY MOOD MOOI MOOK MOOL MOON MOOP MOORMOOS MOOT MOPE MOPS MOPY MORA MORE MORN MORS MORT MOSE MOSH MOSKMOSS MOST MOTE MOTH MOTI MOTS MOTT MOTU MOUE MOUP MOUS MOVE MOWAMOWN MOWS MOXA MOYA MOYL MOYS MOZE MOZO MOZZ MUCH MUCK MUDS MUFFMUGG MUGS MUID MUIL MUIR MULE MULL MUMM MUMP MUMS MUMU MUNG MUNIMUNS MUNT MUON MURA MURE MURK MURL MURR MUSE MUSH MUSK MUSO MUSSMUST MUTE MUTI MUTS MUTT MUZZ MYAL MYCS MYNA MYTH MYXO MZEE NAAMNAAN NABE NABK NABS NACH NADA NADS NAFF NAGA NAGS NAIF NAIK NAILNAIN NALA NAME NAMS NAMU NANA NANE NANS NAOI NAOS NAPA NAPE NAPSNARC NARD NARE NARK NARY NATS NAVE NAVY NAYS NAZE NAZI NEAL NEAPNEAR NEAT NEBS NECK NEDS NEED NEEM NEEP NEFS NEGS NEIF NEKS NEMANEMN NENE NEON NEPS NERD NERK NESH NESS NEST NETE NETS NETT NEUKNEUM NEVE NEVI NEWS NEWT NEXT NIBS NICE NICK NIDE NIDI NIDS NIEDNIEF NIES NIFE NIFF NIGH NILL NILS NIMB NIMS NINE NIPA NIPS NIRLNISH NISI NITE NITS NIXE NIXY NOAH NOBS NOCK NODE NODI NODS NOELNOES NOGG NOGS NOIL NOIR NOLE NOLL NOLO NOMA NOME NOMS NONA NONENONG NONI NOOK NOON NOOP NOPE NORI NORK NORM NOSE NOSH NOSY NOTANOTE NOTT NOUL NOUN NOUP NOUS NOUT NOVA NOWL NOWN NOWS NOWT NOWYNOYS NUBS NUDE NUFF NUKE NULL NUMB NUNS NURD NURL NURR NURS NUTSNYAS NYED NYES OAFS OAKS OAKY OARS OARY OAST OATH OATS OBAS OBESOBEY OBIA OBIS OBIT OBOE OBOL OBOS OCAS OCCY OCHE OCTA ODAH ODALODAS ODDS ODEA ODES ODIC ODOR ODSO ODYL OFAY OFFS OGAM OGEE OGLEOGRE OHED OHIA OHMS OHOS OIKS OILS OILY OINK OINT OKAS OKAY OKEHOKES OKRA OKTA OLDS OLDY OLEA OLEO OLES OLID OLIO OLLA OLMS OLPEOMBU OMEN OMER OMIT OMOV ONCE ONER ONES ONIE ONLY ONOS ONST ONTOONUS ONYX OOFS OOFY OOHS OOMS OONS OONT OOPS OOSE OOSY OOTS OOZEOOZY OPAH OPAL OPED OPEN OPES OPPO OPTS OPUS ORAD ORAL ORBS ORBYORCA ORCS ORDO ORDS ORES ORFE ORFS ORGY ORLE ORRA ORTS ORYX ORZOOSAR OSES OSSA OTIC OTTO OUCH OUDS OUKS OULD OULK OUMA OUPA OUPHOUPS OURN OURS OUST OUTS OUZO OVAL OVEL OVEN OVER OVUM OWED OWEROWES OWLS OWLY OWNS OWRE OWSE OWTS OXEN OXER OXES OXID OXIM OYEROYES OYEZ PAAL PACA PACE PACK PACO PACS PACT PACY PADI PADS PAGEPAHS PAID PAIK PAIL PAIN PAIR PAIS PALE PALL PALM PALP PALS PALYPAMS PAND PANE PANG PANS PANT PAPA PAPE PAPS PARA PARD PARE PARKPARP PARR PARS PART PASE PASH PASS PAST PATE PATH PATS PATU PATYPAUA PAUL PAVE PAVS PAWA PAWK PAWL PAWN PAWS PAYS PEAG PEAK PEALPEAN PEAR PEAS PEAT PEBA PECH PECK PECS PEDS PEED PEEK PEEL PEENPEEP PEER PEES PEGH PEGS PEHS PEIN PEKE PELA PELE PELF PELL PELTPEND PENE PENI PENK PENS PENT PEON PEPO PEPS PERE PERI PERK PERMPERN PERP PERT PERV PESO PEST PETS PEWS PFFT PFUI PHAT PHEW PHISPHIZ PHOH PHON PHOS PHOT PHUT PIAL PIAN PIAS PICA PICE PICK PICSPIED PIER PIES PIET PIGS PIKA PIKE PIKI PILA PILE PILI PILL PILYPIMA PIMP PINA PINE PING PINK PINS PINT PINY PION PIOY PIPA PIPEPIPI PIPS PIPY PIRL PIRN PIRS PISE PISH PISO PISS PITA PITH PITSPITY PIUM PIXY PIZE PLAN PLAP PLAT PLAY PLEA PLEB PLED PLEW PLEXPLIE PLIM PLOD PLOP PLOT PLOW PLOY PLUE PLUG PLUM PLUS POAS POCKPOCO PODS POEM POEP POET POGO POGY POIS POKE POKY POLE POLK POLLPOLO POLS POLT POLY POME POMO POMP POMS POND PONE PONG PONK PONSPONT PONY POOD POOF POOH POOK POOL POON POOP POOR POOS POOT POPEPOPS PORE PORK PORN PORT PORY POSE POSH POSS POST POSY POTE POTSPOTT POUF POUK POUR POUT POWN POWS POXY POZZ PRAD PRAM PRAO PRATPRAU PRAY PREE PREM PREP PREX PREY PREZ PRIG PRIM PROA PROB PRODPROF PROG PROM PROO PROP PROS PROW PRUH PRYS PSIS PSST PTUI PUBEPUBS PUCE PUCK PUDS PUDU PUER PUFF PUGH PUGS PUHA PUIR PUJA PUKAPUKE PUKU PULA PULE PULI PULK PULL PULP PULS PULU PULY PUMA PUMPPUMY PUNA PUNG PUNK PUNS PUNT PUNY PUPA PUPS PUPU PURE PURI PURLPURR PURS PUSH PUSS PUTS PUTT PUTZ PUYS PYAS PYAT PYES PYET PYICPYIN PYNE PYOT PYRE PYRO QADI QAID QATS QOPH QUAD QUAG QUAI QUATQUAY QUEP QUEY QUID QUIM QUIN QUIP QUIT QUIZ QUOD QUOP RABI RACARACE RACH RACK RACY RADE RADS RAFF RAFT RAGA RAGE RAGG RAGI RAGSRAHS RAIA RAID RAIK RAIL RAIN RAIS RAIT RAJA RAKE RAKI RAKU RALERAMI RAMP RAMS RANA RAND RANG RANI RANK RANT RAPE RAPS RAPT RARERARK RASE RASH RASP RAST RATA RATE RATH RATO RATS RATU RAUN RAVERAWN RAWS RAYA RAYS RAZE RAZZ READ REAK REAL REAM REAN REAP REARREBS RECK RECS REDD REDE REDO REDS REED REEF REEK REEL REEN REESREFS REFT REGO REGS REHS REIF REIK REIN REIS REKE RELY REMS RENDRENK RENS RENT RENY REOS REPO REPP REPS RESH REST RETE RETS REVSREWS RHEA RHOS RHUS RIAL RIAS RIBA RIBS RICE RICH RICK RICY RIDERIDS RIEL RIEM RIFE RIFF RIFS RIFT RIGG RIGS RILE RILL RIMA RIMERIMS RIMU RIMY RIND RINE RING RINK RINS RIOT RIPE RIPP RIPS RIPTRISE RISK RISP RITE RITS RITT RITZ RIVA RIVE RIVO RIZA ROAD ROAMROAN ROAR ROBE ROBS ROCH ROCK ROCS RODE RODS ROED ROES ROIL ROINROJI ROKE ROKS ROKY ROLE ROLF ROLL ROMA ROMP ROMS RONE RONG RONTROOD ROOF ROOK ROOM ROON ROOP ROOS ROOT ROPE ROPY RORE RORT RORYROSE ROST ROSY ROTA ROTE ROTI ROTL ROTO ROTS ROUE ROUL ROUM ROUPROUT ROUX ROVE ROWS ROWT RUBE RUBS RUBY RUCK RUCS RUDD RUDE RUDSRUED RUER RUES RUFF RUGA RUGS RUIN RUKH RULE RULY RUME RUMP RUMSRUND RUNE RUNG RUNS RUNT RURP RURU RUSA RUSE RUSH RUSK RUST RUTHRUTS RYAL RYAS RYES RYFE RYKE RYND RYOT RYPE SABE SABS SACK SACSSADE SADI SADO SADS SAFE SAFT SAGA SAGE SAGO SAGS SAGY SAIC SAIDSAIL SAIM SAIN SAIR SAIS SAKE SAKI SALE SALL SALP SALS SALT SAMASAME SAMP SAMS SAND SANE SANG SANK SANS SANT SAPS SARD SARI SARKSARS SASH SASS SATE SATI SAUL SAUT SAVE SAVS SAWN SAWS SAXE SAYSSCAB SCAD SCAG SCAM SCAN SCAR SCAT SCAW SCOG SCOP SCOT SCOW SCRYSCUD SCUG SCUL SCUM SCUP SCUR SCUT SCYE SEAL SEAM SEAN SEAR SEASSEAT SECH SECO SECS SECT SEED SEEK SEEL SEEM SEEN SEEP SEER SEESSEGO SEGS SEIF SEIK SEIL SEIR SEIS SEKT SELD SELE SELF SELL SELSSEME SEMI SENA SEND SENE SENS SENT SEPS SEPT SERA SERE SERF SERKSERR SERS SESE SESH SESS SETA SETS SETT SEWN SEWS SEXT SEXY SEYSSHAD SHAG SHAH SHAM SHAN SHAT SHAW SHAY SHEA SHED SHES SHET SHEWSHIM SHIN SHIP SHIR SHIT SHIV SHMO SHOD SHOE SHOG SHOO SHOP SHOTSHOW SHRI SHUL SHUN SHUT SHWA SIAL SIBB SIBS SICE SICH SICK SICSSIDA SIDE SIDH SIEN SIES SIFT SIGH SIGN SIJO SIKA SIKE SILD SILESILK SILL SILO SILT SIMA SIMI SIMP SIMS SIND SINE SING SINH SINKSINS SIPE SIPS SIRE SIRI SIRS SISS SIST SITE SITH SITS SITZ SIZESIZY SJOE SKAG SKAS SKAT SKAW SKEE SKEG SKEN SKEO SKEP SKER SKETSKEW SKID SKIM SKIN SKIO SKIP SKIS SKIT SKOL SKRY SKUA SKUG SKYFSKYR SLAB SLAE SLAG SLAM SLAP SLAT SLAW SLAY SLED SLEE SLEW SLEYSLID SLIM SLIP SLIT SLOB SLOE SLOG SLOP SLOT SLOW SLUB SLUE SLUGSLUM SLUR SLUT SMEE SMEW SMIR SMIT SMOG SMUG SMUR SMUT SNAB SNAGSNAP SNAR SNAW SNEB SNED SNEE SNIB SNIG SNIP SNIT SNOB SNOD SNOGSNOT SNOW SNUB SNUG SNYE SOAK SOAP SOAR SOBA SOBS SOCA SOCK SOCSSODA SODS SOFA SOFT SOGS SOHO SOHS SOIL SOJA SOKE SOLA SOLD SOLESOLI SOLO SOLS SOMA SOME SOMS SOMY SONE SONG SONS SOOK SOOL SOOMSOON SOOP SOOT SOPH SOPS SORA SORB SORD SORE SORI SORN SORT SOSSSOTH SOTS SOUK SOUL SOUM SOUP SOUR SOUS SOUT SOVS SOWF SOWL SOWMSOWN SOWP SOWS SOYA SOYS SPAE SPAG SPAM SPAN SPAR SPAS SPAT SPAWSPAY SPAZ SPEC SPED SPEK SPET SPEW SPIC SPIE SPIF SPIK SPIM SPINSPIT SPIV SPOD SPOT SPRY SPUD SPUE SPUG SPUN SPUR SRIS STAB STAGSTAP STAR STAT STAW STAY STED STEM STEN STEP STET STEW STEY STIESTIM STIR STOA STOB STOP STOT STOW STUB STUD STUM STUN STYE SUBASUBS SUCH SUCK SUDD SUDS SUED SUER SUES SUET SUGH SUID SUIT SUKHSUKS SULK SULU SUMO SUMP SUMS SUMY SUNG SUNK SUNN SUNS SUPE SUPSSUQS SURA SURD SURE SURF SUSS SUSU SWAB SWAD SWAG SWAM SWAN SWAPSWAT SWAY SWEE SWEY SWIG SWIM SWIZ SWOB SWOP SWOT SWUM SYBO SYCESYED SYEN SYES SYKE SYLI SYNC SYND SYNE SYPE SYPH TAAL TABI TABSTABU TACE TACH TACK TACO TACT TADS TAED TAEL TAES TAGS TAHA TAHRTAIG TAIL TAIN TAIS TAIT TAKA TAKE TAKI TAKS TAKY TALA TALC TALETALI TALK TALL TAME TAMP TAMS TANA TANE TANG TANH TANK TANS TAOSTAPA TAPE TAPS TAPU TARA TARE TARN TARO TARP TARS TART TASH TASKTASS TATE TATH TATS TATT TATU TAUS TAUT TAVA TAVS TAWA TAWS TAWTTAXA TAXI TAYS TEAD TEAK TEAL TEAM TEAR TEAS TEAT TECH TECS TEDSTEDY TEED TEEK TEEL TEEM TEEN TEER TEES TEFF TEFS TEGG TEGS TEGUTEHR TEIL TELA TELD TELE TELL TELS TELT TEME TEMP TEMS TEND TENETENS TENT TEPA TERF TERM TERN TEST TETE TETH TETS TEWS TEXT THAETHAN THAR THAT THAW THEE THEM THEN THEW THEY THIG THIN THIO THIRTHIS THON THOU THRO THRU THUD THUG THUS TIAR TICE TICH TICK TICSTIDE TIDS TIDY TIED TIER TIES TIFF TIFT TIGE TIGS TIKA TIKE TIKITILE TILL TILS TILT TIME TIND TINE TING TINK TINS TINT TINY TIPITIPS TIPT TIRE TIRL TIRO TIRR TITE TITI TITS TIVY TIZZ TOAD TOBYTOCK TOCO TOCS TODS TODY TOEA TOED TOES TOEY TOFF TOFT TOFU TOGATOGE TOGS TOHO TOIL TOIT TOKE TOKO TOLA TOLD TOLE TOLL TOLT TOLUTOMB TOME TOMO TOMS TONE TONG TONK TONS TONY TOOK TOOL TOOM TOONTOOT TOPE TOPH TOPI TOPO TOPS TORA TORC TORE TORI TORN TORO TORRTORS TORT TORY TOSA TOSE TOSH TOSS TOST TOTE TOTS TOUK TOUN TOURTOUT TOWN TOWS TOWT TOWY TOYO TOYS TOZE TRAD TRAM TRAP TRAT TRAYTREE TREF TREK TRES TRET TREW TREY TREZ TRIE TRIG TRIM TRIN TRIOTRIP TROD TROG TRON TROP TROT TROW TROY TRUE TRUG TRYE TRYP TSARTSKS TUAN TUBA TUBE TUBS TUCK TUFA TUFF TUFT TUGS TUIS TULE TUMPTUMS TUNA TUND TUNE TUNG TUNS TUNY TUPS TURD TURF TURK TURM TURNTUSH TUSK TUTS TUTU TUZZ TWAE TWAL TWAS TWAT TWAY TWEE TWIG TWINTWIT TWOS TYDE TYED TYEE TYER TYES TYGS TYIN TYKE TYMP TYND TYNETYPE TYPO TYPP TYPY TYRE TYRO TYTE TZAR UDAL UDON UDOS UEYS UFOSUGHS UGLY UKES ULAN ULES ULEX ULNA ULUS ULVA UMBO UMPH UMPS UMPYUNAI UNAU UNBE UNCE UNCI UNCO UNDE UNDO UNDY UNIS UNIT UNTO UPASUPBY UPDO UPGO UPON UPSY UPTA URAO URBS URDE URDS URDY UREA URESURGE URIC URNS URPS URSA URUS URVA USED USER USES UTAS UTES UTISUTUS UVAE UVAS UVEA VACS VADE VAES VAGI VAGS VAIL VAIN VAIR VALEVALI VAMP VANE VANG VANS VANT VARA VARE VARS VARY VASA VASE VASTVATS VATU VAUS VAUT VAVS VAWS VEAL VEEP VEER VEES VEGA VEGO VEHMVEIL VEIN VELA VELD VELE VELL VENA VEND VENT VERA VERB VERD VERSVERT VERY VEST VETO VETS VEXT VIAE VIAL VIAS VIBE VIBS VICE VIDEVIDS VIED VIER VIES VIEW VIGA VIGS VILD VILE VILL VIMS VINA VINEVINO VINS VINT VINY VIOL VIRE VIRL VISA VISE VITA VITE VIVA VIVEVIVO VIZY VLEI VOAR VOES VOID VOLA VOLE VOLK VOLS VOLT VORS VOTEVOWS VRIL VROT VROU VROW VUGG VUGH VUGS VULN VUMS WAAC WABS WACKWADD WADE WADI WADS WADT WADY WAES WAFF WAFT WAGE WAGS WAID WAIFWAIL WAIN WAIR WAIS WAIT WAKA WAKE WAKF WALD WALE WALI WALK WALLWALY WAME WAND WANE WANG WANK WANS WANT WANY WAPS WAQF WARB WARDWARE WARK WARM WARN WARP WARS WART WARY WASE WASH WASM WASP WASTWATE WATS WATT WAUK WAUL WAUR WAVE WAVY WAWA WAWE WAWL WAWS WAXYWAYS WEAK WEAL WEAN WEAR WEBS WEDS WEED WEEK WEEL WEEM WEEN WEEPWEER WEES WEET WEFT WEID WEIL WEIR WEKA WELD WELK WELL WELT WEMBWEMS WENA WEND WENS WENT WEPT WERE WERO WERT WEST WETA WETS WEXEWEYS WHAE WHAM WHAP WHAT WHEE WHEN WHET WHEW WHEY WHID WHIG WHIMWHIN WHIO WHIP WHIR WHIT WHIZ WHOA WHOM WHOP WHOT WHOW WHUP WHYSWICE WICH WICK WIDE WIEL WIFE WIGS WILD WILE WILI WILL WILT WILYWIMP WIND WINE WING WINK WINN WINO WINS WINY WIPE WIRE WIRY WISEWISH WISP WISS WIST WITE WITH WITS WIVE WOAD WOCK WOES WOFS WOGSWOKE WOKS WOLD WOLF WOMB WONK WONS WONT WOOD WOOF WOOL WOON WOOSWOOT WOPS WORD WORE WORK WORM WORN WORT WOST WOTS WOVE WOWF WOWSWRAP WREN WRIT WUDS WUDU WULL WUSS WYCH WYES WYLE WYND WYNN WYNSWYTE XYST YAAR YABA YACK YADS YAFF YAGI YAGS YAHS YAKS YALD YALEYAMS YANG YANK YAPP YAPS YARD YARE YARK YARN YARR YATE YAUD YAUPYAWL YAWN YAWP YAWS YAWY YAYS YBET YEAD YEAH YEAN YEAR YEAS YEBOYECH YEDE YEED YEGG YELD YELK YELL YELM YELP YELT YENS YEPS YERDYERK YESK YEST YETI YETT YEUK YEVE YEWS YGOE YIDS YIKE YILL YINSYIPE YIPS YIRD YIRK YIRR YITE YLEM YLKE YMPE YMPT YOBS YOCK YODEYODH YODS YOGA YOGH YOGI YOKE YOKS YOLD YOLK YOMP YOND YONI YONTYOOF YOOP YORE YORK YORP YOUK YOUR YOUS YOWE YOWL YOWS YUAN YUCAYUCH YUCK YUFT YUGA YUGS YUKE YUKO YUKS YUKY YULE YUMP YUNX YUPSYURT YUTZ YUZU YWIS ZACK ZAGS ZANY ZAPS ZARF ZATI ZEAL ZEAS ZEBUZEDS ZEES ZEIN ZEKS ZELS ZEPS ZERK ZERO ZEST ZETA ZEZE ZHOS ZIFFZIGS ZILA ZILL ZIMB ZINC ZINE ZING ZINS ZIPS ZITE ZITI ZITS ZIZZZOBO ZOBU ZOEA ZOIC ZOLS ZONA ZONE ZONK ZOOM ZOON ZOOS ZOOT ZORIZOUK ZULU ZUPA ZURF ZYGA ZYME ZZZS";

        String[] arrayWords = words.split(" ");

        Log.i("MYLOG","The array length is "+arrayWords.length);

        int randomNumber = (int) (Math.random() * arrayWords.length);

        String randomWord = arrayWords[randomNumber];

        mWord = randomWord;
    }


    public void clearScreen(){
        TextView textViewFailed = (TextView) findViewById(R.id.textView6);

        textViewFailed.setText("");

        mGuessedLetters = 0;

        mFailCounter = 0;

        LinearLayout layoutLetters = (LinearLayout) findViewById(R.id.layoutLetters);

        int n = layoutLetters.getChildCount();

        for (int i = 0; i < n ; i++) {

            TextView currentTextView = (TextView) layoutLetters.getChildAt(i);

            currentTextView.setText("_");
        }

        ImageView imageView = (ImageView) findViewById(R.id.imageView);

        imageView.setImageResource(R.drawable.hangdroid_0);

    }



    public void letterFailed(String letterFailed){

        TextView textViewFailed = (TextView) findViewById(R.id.textView6);

        String previousFail  = textViewFailed.getText().toString();

        textViewFailed.setText(previousFail + letterFailed);

        mFailCounter++;

        ImageView imageView = (ImageView) findViewById(R.id.imageView);

        int resId = -1;

        switch (mFailCounter){
            case 0: resId = R.drawable.hangdroid_0; break;
            case 1: resId = R.drawable.hangdroid_1; break;
            case 2: resId = R.drawable.hangdroid_2; break;
            case 3: resId = R.drawable.hangdroid_3; break;
            case 4: resId = R.drawable.hangdroid_4; break;
            case 5: resId = R.drawable.hangdroid_5; break;
            case 6:
            default:
                Intent gameOverActivity = new Intent(this,GameOverActivity.class);
                gameOverActivity.putExtra("POINTS_IDENTIFIER",mPoints);

                startActivity(gameOverActivity);
                finish();
                return;
        }

        imageView.setImageResource(resId);
    }

    /**
     * Displaying a letter guessed by the user
     *
     * @param position of the letter
     * @param letterGuessed
     */
    public void showLettersAtIndex(int position,char letterGuessed){
        LinearLayout layoutLetters = (LinearLayout) findViewById(R.id.layoutLetters);

        TextView textView = (TextView) layoutLetters.getChildAt(position);

        textView.setText(Character.toString(letterGuessed));

    }

}
